### ISSUE TITLE
Could not vectorize no docstring codes

### ISSUE THREAD

**Issue by Ceceu** [hamelsmu/code_search#47]
Hello,

I am running [notebook 4](https://github.com/hamelsmu/code_search/blob/master/notebooks/4%20-%20Train%20Model%20To%20Map%20Code%20Embeddings%20to%20Language%20Embeddings.ipynb), the part where codes whithout docstrings are turned into embeddings. Specifically I am having trouble executing the following code snippet:

```
encinp = enc_pp.transform_parallel(no_docstring_funcs)
np.save(code2emb_path/'nodoc_encinp.npy', encinp)
```

which returns the following error:

```
WARNING:root:...tokenizing data
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/multiprocess/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.6/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/conda/lib/python3.6/site-packages/ktext/preprocess.py", line 88, in process_text
    return [tokenizer(cleaner(doc)) for doc in text]
  File "/opt/conda/lib/python3.6/site-packages/ktext/preprocess.py", line 88, in <listcomp>
    return [tokenizer(cleaner(doc)) for doc in text]
  File "/opt/conda/lib/python3.6/site-packages/ktext/preprocess.py", line 55, in textacy_cleaner
    no_accents=True)
  File "/opt/conda/lib/python3.6/site-packages/textacy/preprocess.py", line 256, in preprocess_text
    text = replace_urls(text)
  File "/opt/conda/lib/python3.6/site-packages/textacy/preprocess.py", line 101, in replace_urls
    return constants.RE_URL.sub(
AttributeError: module 'textacy.constants' has no attribute 'RE_URL'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/ktext/preprocess.py in apply_parallel(func, data, cpu_cores)
     71         pool = Pool(cpu_cores)
---> 72         transformed_data = pool.map(func, chunked(data, chunk_size), chunksize=1)
     73     finally:

/opt/conda/lib/python3.6/site-packages/multiprocess/pool.py in map(self, func, iterable, chunksize)
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 

/opt/conda/lib/python3.6/site-packages/multiprocess/pool.py in get(self, timeout)
    643         else:
--> 644             raise self._value
    645 

AttributeError: module 'textacy.constants' has no attribute 'RE_URL'

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-19-8e34745b4d23> in <module>
----> 1 encinp = enc_pp.transform_parallel(test_codes[:5])
      2 np.save(code2emb_path/'test_codes_encinp.npy', encinp)

/opt/conda/lib/python3.6/site-packages/ktext/preprocess.py in transform_parallel(self, data)
    375         """
    376         logging.warning(f'...tokenizing data')
--> 377         tokenized_data = self.parallel_process_text(data)
    378         logging.warning(f'...indexing data')
    379         indexed_data = self.indexer.tokenized_texts_to_sequences(tokenized_data)

/opt/conda/lib/python3.6/site-packages/ktext/preprocess.py in parallel_process_text(self, data)
    231                                                 end_tok=self.end_tok)
    232         n_cores = self.num_cores
--> 233         return flattenlist(apply_parallel(process_text, data, n_cores))
    234 
    235     def generate_doc_length_stats(self):

/opt/conda/lib/python3.6/site-packages/ktext/preprocess.py in apply_parallel(func, data, cpu_cores)
     74         pool.close()
     75         pool.join()
---> 76         return transformed_data
     77 
     78 

UnboundLocalError: local variable 'transformed_data' referenced before assignment
```

Thanks in Advance.

**Comment by Ceceu** [comment]
The error only happened because of the difference in the Spacy version.
