### ISSUE TITLE
Facing error while executing ->   from fastai.text import *

### ISSUE THREAD

**Issue by niteshjindal170988** [hamelsmu/code_search#69]
I am facing below error:
[errofile.txt](https://github.com/hamelsmu/code_search/files/4603350/errofile.txt)

 from fastai import text
Traceback (most recent call last):

  File "<ipython-input-28-4ac904707a2a>", line 1, in <module>
    from fastai import text

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\__init__.py", line 1, in <module>
    from .. import basics

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\basics.py", line 1, in <module>
    from .basic_train import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\basic_train.py", line 2, in <module>
    from .torch_core import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\torch_core.py", line 2, in <module>
    from .imports.torch import *

ModuleNotFoundError: No module named 'fastai.imports.torch'; 'fastai.imports' is not a package

from fastai.text import *
Traceback (most recent call last):

  File "<ipython-input-29-55ea5f35b797>", line 1, in <module>
    from fastai.text import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\__init__.py", line 1, in <module>
    from .. import basics

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\basics.py", line 1, in <module>
    from .basic_train import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\basic_train.py", line 2, in <module>
    from .torch_core import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\torch_core.py", line 2, in <module>
    from .imports.torch import *

ModuleNotFoundError: No module named 'fastai.imports.torch'; 'fastai.imports' is not a package

from fastai.text import *
Traceback (most recent call last):

  File "<ipython-input-30-55ea5f35b797>", line 1, in <module>
    from fastai.text import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\__init__.py", line 1, in <module>
    from .. import basics

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\basics.py", line 1, in <module>
    from .basic_train import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\basic_train.py", line 2, in <module>
    from .torch_core import *

  File "C:\Users\NJ077229\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\torch_core.py", line 2, in <module>
    from .imports.torch import *

ModuleNotFoundError: No module named 'fastai.imports.torch'; 'fastai.imports' is not a package

**Comment by hamelsmu** [comment]
**The techniques presented here are old and have been significantly refined in a subsequent project called [CodeSearchNet](https://github.com/github/codesearchnet), with an associated [paper](https://arxiv.org/abs/1909.09436).**

I recommend looking at the aforementioned project for a more modern approach to this topic
